# Generated by Django 4.2.2 on 2023-06-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=500)),
                ('productcategory', models.CharField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
